name: Publish Package to npmjs
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mymindstorm/setup-emsdk@v11
            - name: Verify
              run: emcc --version
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci --legacy-peer-deps
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
